name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm test
             - name: Login to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Push to Docker Hub
        run: |
          docker tag aniket:v1 ${{ secrets.DOCKER_USERNAME }}/ci-cd-demo:latest
          docker push ${{ secrets.DOCKER_USERNAME }}/ci-cd-demo:latest

      - name: Build Docker image
        run: docker build -t aniket:v1 .

